window.defaultNumber = '+1-877-765-4146';
window.defaultText='Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)';
window.text ={
	'xhamster.com':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'perfectgirls.net':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'gotporn.com':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'anysex.com':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'sex.com':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'bravotube.net':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'mylust.com':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'manporn.xxx':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'anybunny.com':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'txxx.com':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)',
	'findbestsolution.xyz':'Apple Security Alert- Waring iOS Crash Report Suspicious Activity Detected Error code:- apphac065h Malicious application detected by apple scan and there has been a hacking alert on your account. your personal and financial information is at risk major security issue. Contact Apple Support for an immediate fix +1-877-765-4146(toll free)'
};
